version: '3.8'

services:
  shareit:
    restart: on-failure
    container_name: shareit
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/share_it
      SPRING_DATASOURCE_USERNAME: shareitadmin
      SPRING_DATASOURCE_PASSWORD: root
    ports:
      - 9090:9090
    depends_on:
      - database

  database:
    image: postgres:17.2-alpine3.21
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: shareitadmin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: share_it
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: