name: Tests with maven

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Cache Maven dependencies
      uses: actions/cache@v4
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

#    - name: Build and test with Maven
#      run: mvn clean test --batch-mode

    - name: Create coverage reports
      run: mvn -B verify --file pom.xml

    - name: Run codacy-coverage-reporter
      uses: codacy/codacy-coverage-reporter-action@v1.3
      with:
        coverage-reports: ./target/site/jacoco/jacoco.xml
        project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}